### ISSUE TITLE
Changing a translation crashes the app during development!

### ISSUE THREAD

**Issue by BerndWessels** [AlexanderZaytsev/react-native-i18n#59] opened 2017-02-08 20:20 UTC
Hi
I wonder if I am doing something wrong or if this is a bug.
When I change a translation string like in `english.json` I change
`"welcome": "Welcome",`
to
`"welcome": "Welcomeeee",`
The app crashes with the following error:
```
Unexpected token :handleException @ C:\git\awhina\node_modules\react-native\Libraries\Core\ExceptionsManager.js:63handleError @ C:\git\awhina\node_modules\react-native\Libraries\Core\InitializeCore.js:114reportFatalError @ C:\git\awhina\node_modules\react-native\packager\react-packager\src\Resolver\polyfills\error-guard.…:44guard @ C:\git\awhina\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:48callFunctionReturnFlushedQueue @ C:\git\awhina\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:107message @ index.js:73
```
which might originate from here
```
message	@	RNDebuggerWorker.js:123
        ...
        returnValue = __fbBatchedBridge[object.method].apply(null, object.arguments);
        ...
```

This makes it a very unpleasant development experience.

Any idea how to fix this?

**Comment by mmazzarolo** [comment] 2017-02-21 20:21
Hey @BerndWessels, are you still having the issue?  
If the issue is still there, would you mind trying with a `js` file instead of a `json` one?

**Comment by unicornRainbows** [comment] 2017-02-22 08:24
mmmm @mmazzarolo im also having the issue, tried with js but no luck..

**Comment by zoontek** [comment] 2017-08-29 22:36
I'm closing this since I can't reproduce the error with the latest version.

**Closed by zoontek** 2017-08-29 22:36 UTC
