### ISSUE TITLE
Undefined is not an object (evaluating 'RNI18n.getLanguages')

### ISSUE THREAD

**Issue by BrettBukowski** [AlexanderZaytsev/react-native-i18n#149] opened 2017-11-28 04:27 UTC
This is the same as <https://github.com/AlexanderZaytsev/react-native-i18n/issues/114> and <https://github.com/AlexanderZaytsev/react-native-i18n/issues/130>, which were closed without a solution.

This appears to be a linking issue, since the 'react-native-i18n module is not correctly linked' warning message is logged to the console.

Steps:

(following the setup instructions from the readme)

React Native - 0.37.0
Xcode 9.1

1. `npm install react-native-i18n --save`
2. `react-native link`
3. `react-native run-ios`
4. Import a file in your project that contains `import I18n from 'react-native-i18n';`

<img width="374" alt="screen shot 2017-11-27 at 8 21 54 pm" src="https://user-images.githubusercontent.com/224622/33302455-138c81ca-d3b1-11e7-9148-3e40832f383f.png">

When manually building the project from Xcode and not through the react native cli, everything works fine.

**Comment by Benorb** [comment] 2017-11-29 12:34
Im having this issue too.

**Comment by sabbyt54** [comment] 2017-12-03 14:24
+1

**Comment by rajivshah3** [comment] 2017-12-04 02:06
I think `react-native link` has been breaking builds recently

**Comment by mobihunterz** [comment] 2017-12-09 09:56
For me as well the error occurs. Although build works fine with XCode as mentioned.

This is why native development seems to be best option.

**Comment by giantss** [comment] 2017-12-11 11:52
+1

**Comment by esutton** [comment] 2017-12-15 03:59
+1

I understand **react-native link** will modify your Podfile if your dependent packages contain a podspec.

I assume this means the react-native-i18n podspec is broken?

**Comment by zoontek** [comment] 2017-12-21 11:10
It should be fixed in the new version: https://github.com/AlexanderZaytsev/react-native-i18n/releases/tag/v2.1.0 :)

**Closed by zoontek** 2017-12-21 11:10 UTC

**Comment by wadim** [comment] 2018-03-08 08:36
@zoontek What happened with the version? The link doesn't work and I can't find the version.

**Comment by MeKyleH** [comment] 2018-03-09 05:35
So was it fixed? The post by @zoontek says it will be fixed in v2.2.0 but I see the latest version as 2.0.12. Any way we can help to fix?

**Comment by zoontek** [comment] 2018-03-10 11:14
The version introduce a regression. The next version was the one linked.

**Comment by zoontek** [comment] 2018-03-10 11:15
Are you all using a Podfile?

**Comment by MeKyleH** [comment] 2018-03-10 20:38
I'm using Expo, so no Podfiles for me :).

**Comment by zoontek** [comment] 2018-03-10 20:45
You can't use this lib with Expo, that's probably why :)
